### ISSUE TITLE
pylint ignores max-line-length

### ISSUE THREAD

**Issue by zloy531** [PyCQA/prospector#223]
Checking the project with prospector and get the warning:
```
snippets/models.py
  Line: 15
    pylint: line-too-long / Line too long (91/79)
  Line: 16
    pylint: line-too-long / Line too long (86/79)
```

My `.prospector.yaml`:
```
strictness: veryhigh
pylint:
  full: true
pep8:
  full: true
  options:
    max-line-length: 120
uses:
  - django
```
Why pylint ignores `max-line-length`? Django, python3.6, prospector==0.12.7 (and I checked master branch too), pylint==1.7.2.
