### ISSUE TITLE
Very strange behaviour with pylint and pylintrc file.

### ISSUE THREAD

**Issue by 1oglop1** [PyCQA/prospector#227]
My current configuration:
`.prospector.yaml`

```
pep257:
  disable:
    - D203
    - D212
  enable:
    - D213

pep8:
  enable:
    - W601
  options:
    max-line-length: 121

pylint:
  disable:
    - line-too-long  # Already checked by pep8

ignore-paths:
  - _CI
  - build
```

**What is happening:**
I had `.pylintrc` in the project just because of `line-too-long`. 
And this command `prospector -DFM -s veryhigh` gave me 2 pylint warnings about #ToDo and #Fixme, which was desired.

I have moved `line-too-long` to `.prospector.yaml` (as above)
And removed `.pylintrc`.
Then I did not get warnings from pylint.

After putting empty `.pylintrc` back. It worked again
