### ISSUE TITLE
Ability to specify argument-rgx, attr-rgx, function-rgx .etc for pylint in prospector profile?

### ISSUE THREAD

**Issue by fgimian** [PyCQA/prospector#247]
Hey there guys, just trying out your awesome tool.

I set the following in my `pylintrc` usually to allow single letter or longer variable names:

```ini
[BASIC]
# Regular expressions used to match various names (we allow shorter and longer names than default)
# (see http://pylint-messages.wikidot.com/messages:c0103)
argument-rgx = [a-z_][a-z0-9_]*$
attr-rgx = [a-z_][a-z0-9_]*$
function-rgx = [a-z_][a-z0-9_]*$
method-rgx = [a-z_][a-z0-9_]*$
variable-rgx = [a-z_][a-z0-9_]*$
```

Is this configuration possible in a prospector profile currently?

Thanks
Fotis

**Comment by fgimian** [comment]
Just realised that these are supported via `options`:

```yaml
pylint:
  options:
    # Regular expressions used to match various names
    # (we allow shorter and longer names than default)
    argument-rgx: "[a-z_][a-z0-9_]*$"
    attr-rgx: "[a-z_][a-z0-9_]*$"
    function-rgx: "[a-z_][a-z0-9_]*$"
    method-rgx: "[a-z_][a-z0-9_]*$"
    variable-rgx: "[a-z_][a-z0-9_]*$"
  disable:
    - too-many-ancestors
    - too-many-instance-attributes
    - too-few-public-methods
    ...
```

Thanks!
Fotis
