### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by mxlei01** [PyCQA/prospector#258]
OS: Ubuntu 17.10
Python: 3.6.3
Prospector Version: 0.12.11

Libraries:
google-cloud-bigquery
google-cloud-bigquery-datatransfer

These few lines generates a segmentation fault:

```
from google.protobuf import timestamp_pb2

timestamp_start = timestamp_pb2.Timestamp()
```

> 31453 Segmentation fault      (core dumped) prospector --profile-path .prospector.yml

Prospector File:

```
doc-warnings: yes
test-warnings: yes
strictness: veryhigh
autodetect: yes
max-line-length: 120
requirements:
    - requirements.txt
python-targets:
    - 3
pep8:
    full: true
pylint:
    run: true
    disable:
      - too-many-return-statements
      - too-many-instance-attributes
      - too-few-public-methods
      - invalid-name
      - too-many-ancestors
      - unnecessary-lambda
      - expression-not-assigned
      - broad-except
      - too-many-locals
      - too-many-arguments
pep257:
    run: true
    disable:
      - D213
      - D211
      - D406
      - D407
mccabe:
    disable:
      - MC0001
```
