### ISSUE TITLE
Support mypy options in .prospector.yaml

### ISSUE THREAD

**Issue by tjorda01** [PyCQA/prospector#313]
There doesn't seem to be a way to set any mypy options in the .prospector.yaml, or the Prospector command line. Therefore, mypy always runs with its own default configuration whenever it's run within Prospector, for example "prospector --with-tool mypy".

These are just a few variations of the .prospector.yaml settings that I tried without success:
```
mypy:
  options:
    strict: True
    ignore-missing-imports: True
```

```
mypy:
  enable:
    - strict
    - ignore-missing-imports
```

Thanks for your help.

**Comment by chocoelho** [comment]
@tjorda01 as of now, mypy is set work as follow:

```yaml
mypy:
    run: true
    options:
         ignore-missing-imports: true
         follow-imports: skip
         allow:
             - untyped-globals
```
