### ISSUE TITLE
Support pylint --load-plugins option in profile 

### ISSUE THREAD

**Issue by SergeyKosarchuk** [PyCQA/prospector#315]
Hi!
Is `--load-plugins` tool option for pylint supported by [profile](https://prospector.landscape.io/en/master/profiles.html#tool-options) configuration file? Seems like this option has no effect. Here is my `.prospector.yaml` file.

```yaml
pylint:
  disable:
    - unused-argument
    - too-few-public-methods
    - too-many-arguments
    - too-many-ancestors
    - redefined-outer-name
    - relative-beyond-top-level
  load-plugins:
    - custom-plugin
``` 

I am using `prospector==1.1.6.2` and `pylint==2.1.1`.
